version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306" # expose if you want to connect from outside as well
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-prootpass"]
      interval: 5s
      timeout: 3s
      retries: 20
    volumes:
      - db_data:/var/lib/mysql

  web:
    build: .
    container_name: todo_web
    command: python app.py
    environment:
      FLASK_SECRET_KEY: dev-secret
      DB_HOST: db # <-- important: service name, NOT localhost
      DB_PORT: 3306
      DB_USER: appuser
      DB_PASSWORD: apppass
      DB_NAME: todo_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app

volumes:
  db_data:
